import 'package:converterpro/models/currencies.dart';
import 'package:converterpro/models/settings.dart';
import 'package:converterpro/utils/utils.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:units_converter/units_converter.dart';

const Map<String, String> _currenciesSymbols = {
  'AED': 'د.إ assets/flags_opti/ae.svg.vec',
  'AFN': '؋ assets/flags_opti/af.svg.vec',
  'ALL': 'L assets/flags_opti/al.svg.vec',
  'AMD': '֏ assets/flags_opti/am.svg.vec',
  'AOA': 'Kz assets/flags_opti/ao.svg.vec',
  'ARS': '\$ assets/flags_opti/ar.svg.vec',
  'AUD': '\$ assets/flags_opti/au.svg.vec',
  'AWG': 'Afl. assets/flags_opti/aw.svg.vec',
  'AZN': '₼ assets/flags_opti/az.svg.vec',
  'BAM': 'KM assets/flags_opti/ba.svg.vec',
  'BBD': '\$ assets/flags_opti/bb.svg.vec',
  'BDT': '৳ assets/flags_opti/bd.svg.vec',
  'BGN': 'лв assets/flags_opti/bg.svg.vec',
  'BHD': '.د.ب assets/flags_opti/bh.svg.vec',
  'BIF': 'Fr assets/flags_opti/bi.svg.vec',
  'BMD': '\$ assets/flags_opti/bm.svg.vec',
  'BND': '\$ assets/flags_opti/bn.svg.vec',
  'BOB': 'Bs. assets/flags_opti/bo.svg.vec',
  'BRL': 'R\$ assets/flags_opti/br.svg.vec',
  'BSD': '\$ assets/flags_opti/bs.svg.vec',
  'BTN': 'Nu. assets/flags_opti/bt.svg.vec',
  'BWP': 'P assets/flags_opti/bw.svg.vec',
  'BYN': 'Br assets/flags_opti/by.svg.vec',
  'BZD': '\$ assets/flags_opti/bz.svg.vec',
  'CAD': '\$ assets/flags_opti/ca.svg.vec',
  'CDF': 'Fr assets/flags_opti/cd.svg.vec',
  'CHF': 'Fr. assets/flags_opti/ch.svg.vec',
  'CLP': '\$ assets/flags_opti/cl.svg.vec',
  'CNY': '¥ assets/flags_opti/cn.svg.vec',
  'COP': '\$ assets/flags_opti/co.svg.vec',
  'CRC': '₡ assets/flags_opti/cr.svg.vec',
  'CUP': '\$ assets/flags_opti/cu.svg.vec',
  'CVE': '\$ assets/flags_opti/cv.svg.vec',
  'CZK': 'Kč assets/flags_opti/cz.svg.vec',
  'DJF': 'Fr assets/flags_opti/dj.svg.vec',
  'DKK': 'kr assets/flags_opti/dk.svg.vec',
  'DOP': 'RD\$ assets/flags_opti/do.svg.vec',
  'DZD': 'د.ج assets/flags_opti/dz.svg.vec',
  'EGP': 'ج.م assets/flags_opti/eg.svg.vec',
  'ERN': 'Nfk assets/flags_opti/er.svg.vec',
  'ETB': 'Br assets/flags_opti/et.svg.vec',
  'EUR': '€ assets/flags_opti/eu.svg.vec',
  'FJD': '\$ assets/flags_opti/fj.svg.vec',
  'FKP': '£ assets/flags_opti/fk.svg.vec',
  'GBP': '£ assets/flags_opti/gb.svg.vec',
  'GEL': '₾ assets/flags_opti/ge.svg.vec',
  'GHS': '₵ assets/flags_opti/gh.svg.vec',
  'GIP': '£ assets/flags_opti/gi.svg.vec',
  'GMD': 'D assets/flags_opti/gm.svg.vec',
  'GNF': 'Fr assets/flags_opti/gn.svg.vec',
  'GTQ': 'Q assets/flags_opti/gt.svg.vec',
  'GYD': '\$ assets/flags_opti/gy.svg.vec',
  'HKD': '\$ assets/flags_opti/hk.svg.vec',
  'HNL': 'L assets/flags_opti/hn.svg.vec',
  'HRK': 'kn assets/flags_opti/hr.svg.vec',
  'HTG': 'G assets/flags_opti/ht.svg.vec',
  'HUF': 'Ft assets/flags_opti/hu.svg.vec',
  'IDR': 'Rp assets/flags_opti/id.svg.vec',
  'ILS': '₪ assets/flags_opti/il.svg.vec',
  'INR': '₹ assets/flags_opti/in.svg.vec',
  'IQD': 'ع.د assets/flags_opti/iq.svg.vec',
  'IRR': '﷼ assets/flags_opti/ir.svg.vec',
  'ISK': 'kr assets/flags_opti/is.svg.vec',
  'JMD': '\$ assets/flags_opti/jm.svg.vec',
  'JOD': 'د.أ assets/flags_opti/jo.svg.vec',
  'JPY': '¥ assets/flags_opti/jp.svg.vec',
  'KES': 'Sh assets/flags_opti/ke.svg.vec',
  'KGS': 'С̲ assets/flags_opti/kg.svg.vec',
  'KHR': '៛ assets/flags_opti/kh.svg.vec',
  'KMF': 'Fr assets/flags_opti/km.svg.vec',
  'KRW': '₩ assets/flags_opti/kr.svg.vec',
  'KWD': 'د.ك assets/flags_opti/kw.svg.vec',
  'KYD': '\$ assets/flags_opti/ky.svg.vec',
  'KZT': '₸ assets/flags_opti/kz.svg.vec',
  'LAK': '₭ assets/flags_opti/la.svg.vec',
  'LBP': 'ل.ل. assets/flags_opti/lb.svg.vec',
  'LKR': 'Rs assets/flags_opti/lk.svg.vec',
  'LRD': '\$ assets/flags_opti/lr.svg.vec',
  'LSL': 'L assets/flags_opti/ls.svg.vec',
  'LYD': 'ل.د assets/flags_opti/ly.svg.vec',
  'MAD': 'د.م. assets/flags_opti/ma.svg.vec',
  'MDL': 'L assets/flags_opti/md.svg.vec',
  'MGA': 'Ar assets/flags_opti/mg.svg.vec',
  'MKD': 'ден assets/flags_opti/mk.svg.vec',
  'MMK': 'Ks assets/flags_opti/mm.svg.vec',
  'MNT': '₮ assets/flags_opti/mn.svg.vec',
  'MOP': 'MOP\$ assets/flags_opti/mo.svg.vec',
  'MRU': 'UM assets/flags_opti/mr.svg.vec',
  'MUR': '₨ assets/flags_opti/mu.svg.vec',
  'MVR': '.ރ assets/flags_opti/mv.svg.vec',
  'MWK': 'MK assets/flags_opti/mw.svg.vec',
  'MXN': '\$ assets/flags_opti/mx.svg.vec',
  'MYR': 'RM assets/flags_opti/my.svg.vec',
  'MZN': 'MT assets/flags_opti/mz.svg.vec',
  'NAD': '\$ assets/flags_opti/na.svg.vec',
  'NGN': '₦ assets/flags_opti/ng.svg.vec',
  'NIO': 'C\$ assets/flags_opti/ni.svg.vec',
  'NOK': 'kr assets/flags_opti/no.svg.vec',
  'NPR': 'रु assets/flags_opti/np.svg.vec',
  'NZD': '\$ assets/flags_opti/nz.svg.vec',
  'OMR': 'ر.ع. assets/flags_opti/om.svg.vec',
  'PAB': 'B/. assets/flags_opti/pa.svg.vec',
  'PEN': 'S/ assets/flags_opti/pe.svg.vec',
  'PGK': 'K assets/flags_opti/pg.svg.vec',
  'PHP': '₱ assets/flags_opti/ph.svg.vec',
  'PKR': '₨ assets/flags_opti/pk.svg.vec',
  'PLN': 'zł assets/flags_opti/pl.svg.vec',
  'PYG': '₲ assets/flags_opti/py.svg.vec',
  'QAR': 'ر.ق assets/flags_opti/qa.svg.vec',
  'RON': 'lei assets/flags_opti/ro.svg.vec',
  'RSD': 'дин. assets/flags_opti/rs.svg.vec',
  'RUB': '₽ assets/flags_opti/ru.svg.vec',
  'RWF': 'Fr assets/flags_opti/rw.svg.vec',
  'SAR': 'ر.س assets/flags_opti/sa.svg.vec',
  'SBD': ' \$ assets/flags_opti/sb.svg.vec',
  'SCR': '₨ assets/flags_opti/sc.svg.vec',
  'SDG': 'ج.س. assets/flags_opti/sd.svg.vec',
  'SEK': 'kr assets/flags_opti/se.svg.vec',
  'SGD': '\$ assets/flags_opti/sg.svg.vec',
  'SHP': '£ assets/flags_opti/sh.svg.vec',
  'SLE': 'Le assets/flags_opti/sl.svg.vec',
  'SOS': 'Sh assets/flags_opti/so.svg.vec',
  'SRD': '\$ assets/flags_opti/sr.svg.vec',
  'SSP': '£ assets/flags_opti/ss.svg.vec',
  'STN': 'Db assets/flags_opti/st.svg.vec',
  'SYP': 'ل.س assets/flags_opti/sy.svg.vec',
  'SZL': 'L assets/flags_opti/sz.svg.vec',
  'THB': '฿ assets/flags_opti/th.svg.vec',
  'TJS': 'SM assets/flags_opti/tj.svg.vec',
  'TMT': 'm assets/flags_opti/tm.svg.vec',
  'TND': 'د.ت assets/flags_opti/tn.svg.vec',
  'TOP': 'T\$ assets/flags_opti/to.svg.vec',
  'TRY': '₺ assets/flags_opti/tr.svg.vec',
  'TTD': '\$ assets/flags_opti/tt.svg.vec',
  'TWD': '\$ assets/flags_opti/tw.svg.vec',
  'TZS': 'Sh assets/flags_opti/tz.svg.vec',
  'UAH': '₴ assets/flags_opti/ua.svg.vec',
  'UGX': 'Sh assets/flags_opti/ug.svg.vec',
  'USD': '\$ assets/flags_opti/us.svg.vec',
  'UYU': '\$ assets/flags_opti/uy.svg.vec',
  'UZS': 'сўм assets/flags_opti/uz.svg.vec',
  'VES': 'Bs. assets/flags_opti/ve.svg.vec',
  'VND': '₫ assets/flags_opti/vn.svg.vec',
  'VUV': 'Vt assets/flags_opti/vu.svg.vec',
  'WST': 'T assets/flags_opti/ws.svg.vec',
  'XAF': 'FCFA',
  'XDR': 'SDR',
  'XCD': 'EC\$',
  'XCG': 'Cg',
  'XOF': 'CFA',
  'XPF': 'F',
  'YER': 'ر.ي assets/flags_opti/ye.svg.vec',
  'ZAR': 'R assets/flags_opti/za.svg.vec',
  'ZIG': 'ZiG',
  'ZMW': 'ZK assets/flags_opti/zm.svg.vec',
};

final propertiesMapProvider = Provider<Map<PROPERTYX, Property>>(
  (ref) {
    final removeTrailingZeros = ref.watch(removeTrailingZerosProvider).value ?? true;
    final significantFigures = ref.watch(significantFiguresProvider).value ?? 10;
    final exchangeRates = ref
        .watch(CurrenciesNotifier.provider)
        .when(
          data:
              (currencies) => Map<String, double>.fromEntries(
                currencies.exchangeRates.entries.where(
                  (e) => _currenciesSymbols.containsKey(e.key),
                ),
              ),
          error: (_, trace) => Currencies.defaultExchangeRates,
          loading: () => Currencies.defaultExchangeRates,
        );
    return {
      PROPERTYX.length: Length(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.length,
      ),
      PROPERTYX.area: Area(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.area,
      ),
      PROPERTYX.density: Density(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.density,
      ),
      PROPERTYX.volume: Volume(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.volume,
      ),
      PROPERTYX.currencies: SimpleCustomProperty(
        exchangeRates,
        mapSymbols: _currenciesSymbols,
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.currencies,
      ),
      PROPERTYX.time: Time(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.time,
      ),
      PROPERTYX.temperature: Temperature(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.temperature,
      ),
      PROPERTYX.speed: Speed(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.speed,
      ),
      PROPERTYX.mass: Mass(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.mass,
      ),
      PROPERTYX.force: Force(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.force,
      ),
      PROPERTYX.fuelConsumption: FuelConsumption(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.fuelConsumption,
      ),
      PROPERTYX.numeralSystems: NumeralSystems(name: PROPERTYX.numeralSystems),
      PROPERTYX.pressure: Pressure(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.pressure,
      ),
      PROPERTYX.energy: Energy(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.energy,
      ),
      PROPERTYX.power: Power(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.power,
      ),
      PROPERTYX.angle: Angle(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.angle,
      ),
      PROPERTYX.shoeSize: ShoeSize(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.shoeSize,
      ),
      PROPERTYX.digitalData: DigitalData(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.digitalData,
      ),
      PROPERTYX.siPrefixes: SIPrefixes(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.siPrefixes,
      ),
      PROPERTYX.torque: Torque(
        significantFigures: significantFigures,
        removeTrailingZeros: removeTrailingZeros,
        name: PROPERTYX.torque,
      ),
    };
  },
);
